### PR TITLE
Fixes #701

### LINKED ISSUE #701: Wrong metadata, uncompressed_size reflects size of single part of the backup.
In case if tar file is bigger than WALG_TAR_SIZE_THRESHOLD, uncompressed_size stores only size of the last tar file and doesn't include previous parts of tar file.

### PR DESCRIPTION
**Pull request by yanchenko-igor**
@x4m Could you have a look if this is a good approach? It fixes the issue with wrong metadata.

### CODE REVIEW

**Comment by x4m** [comment]
@usernamedt this, probably, interferes much with your work. Can you please review this PR?

File: internal/bundle.go [hunk 1]
```diff
@@ -184,6 +187,7 @@ func (bundle *Bundle) CheckSizeAndEnqueueBack(tarBall TarBall) error {
 		bundle.mutex.Lock()
 		defer bundle.mutex.Unlock()
 
+		atomic.AddInt64(bundle.AllTarballsSize, tarBall.Size())
```
Comment (usernamedt) [inline internal/bundle.go:190]: Seems like this row should be added before each .CloseTar() call, not only in CheckSizeAndEnqueueBack(), but in uploadLabelFiles, UploadPGControl, FinishQueue too

**Comment by usernamedt** [comment]
I've noticed this issue too, fix seems legit except one issue that I commented.

As for my PR https://github.com/wal-g/wal-g/pull/687 there is definitely some interference but since I don't use or change the uncompressedSize logic it seems like OK. Maybe some more merging will be required :)

File: internal/bundle.go (hunk 1 above)
Comment (yanchenko-igor) [reply internal/bundle.go:190]: It wasn't necessary because I used current tarball size together with bundle.AllTarballssize 
```	uncompressedSize := bundle.TarBall.Size() + atomic.LoadInt64(bundle.AllTarballsSize)``` but it will work as well if we do it each time before closing tarball.

Comment (usernamedt) [reply internal/bundle.go:191]: I think it is a good idea to extract this increment to a method to avoid duplication

Comment (yanchenko-igor) [reply internal/bundle.go:191]: yeah, I already pushed the change.

Comment (yanchenko-igor) [reply internal/bundle.go]: fixed that.

File: internal/backup_push_handler.go [hunk 2]
```diff
@@ -128,7 +128,7 @@ func createAndPushBackup(
 	tracelog.ErrorLogger.FatalOnError(err)
 	err = bundle.FinishQueue()
 	tracelog.ErrorLogger.FatalOnError(err)
-	uncompressedSize := bundle.TarBall.Size()
+	uncompressedSize := atomic.LoadInt64(bundle.AllTarballsSize)
 	compressedSize := atomic.LoadInt64(uploader.tarSize)
```
Comment (usernamedt) [inline internal/backup_push_handler.go:132]: These two size assignments are executed before uploadPGControl and uploadlabelfiles tars, I think they should be assigned after.

Comment (yanchenko-igor) [reply internal/backup_push_handler.go]: fixed.

**Comment by usernamedt** [comment]
Seems legit for me

Need a review from someone with write access @x4m

**Comment by x4m** [comment]
@usernamedt you have write access :) Just accept the invite.
