### PR TITLE
Have CompressAndEncrypt's errors wrap the root cause

### LINKED ISSUE #2113: [BUG] CompressAndEncrypt Error message is poor
### Database name

PostgreSQL

### WAL-G Version

v3.0.7

### Describe your problem

caused by: CompressAndEncrypt: compression failed
This error message is kind of bad.

https://github.com/wal-g/wal-g/blob/a3a533c7ec7abbb940cc51506b5eee5cc94d5224/internal/compress_and_encrypt.go#L52-L68
Can these be changed to not throw away err?

### Steps to reproduce

idk man

### Config and WAL-G logs

wal-g-1  | ERROR: 2025/11/19 12:55:08.453875 ReadRequestBody: read upload data failed
wal-g-1  | caused by: CompressAndEncrypt: compression failed
wal-g-1  | github.com/wal-g/wal-g/internal.newCompressingPipeWriterError
wal-g-1  |      /home/runner/work/wal-g/wal-g/internal/compress_and_encrypt.go:21
wal-g-1  | github.com/wal-g/wal-g/internal.CompressAndEncrypt.func1
wal-g-1  |      /home/runner/work/wal-g/wal-g/internal/compress_and_encrypt.go:55
wal-g-1  | runtime.goexit
wal-g-1  |      /opt/hostedtoolcache/go/1.22.12/x64/src/runtime/asm_amd64.s:1695
wal-g-1  | failed to upload 'basebackups_005/base_000000010000000000000042/tar_partitions/part_001.tar.lz4' to bucket 'qddAhsGKklGSBKfL7AB6'
wal-g-1  | github.com/wal-g/wal-g/pkg/storages/s3.(*Uploader).upload
wal-g-1  |      /home/runner/work/wal-g/wal-g/pkg/storages/s3/uploader.go:107
wal-g-1  | github.com/wal-g/wal-g/pkg/storages/s3.(*Folder).PutObjectWithContext
wal-g-1  |      /home/runner/work/wal-g/wal-g/pkg/storages/s3/folder.go:76
wal-g-1  | github.com/wal-g/wal-g/internal/multistorage.Folder.PutObjectToFirst
wal-g-1  |      /home/runner/work/wal-g/wal-g/internal/multistorage/folder.go:460
wal-g-1  | github.com/wal-g/wal-g/internal/multistorage.Folder.PutObjectWithContext
wal-g-1  |      /home/runner/work/wal-g/wal-g/internal/multistorage/folder.go:443
wal-g-1  | github.com/wal-g/wal-g/internal.(*RegularUploader).Upload
wal-g-1  |      /home/runner/work/wal-g/wal-g/internal/uploader.go:178
wal-g-1  | github.com/wal-g/wal-g/internal/databases/postgres.(*StreamingBaseBackup).Upload
wal-g-1  |      /home/runner/work/wal-g/wal-g/internal/databases/postgres/streaming_base_backup.go:135
wal-g-1  | github.com/wal-g/wal-g/internal/databases/postgres.(*BackupHandler).runRemoteBackup
wal-g-1  |      /home/runner/work/wal-g/wal-g/internal/databases/postgres/backup_push_handler.go:553
wal-g-1  | github.com/wal-g/wal-g/internal/databases/postgres.(*BackupHandler).createAndPushRemoteBackup
wal-g-1  |      /home/runner/work/wal-g/wal-g/internal/databases/postgres/backup_push_handler.go:452
wal-g-1  | github.com/wal-g/wal-g/internal/databases/postgres.(*BackupHandler).handleBackupPushRemote
wal-g-1  |      /home/runner/work/wal-g/wal-g/internal/databases/postgres/backup_push_handler.go:407
wal-g-1  | github.com/wal-g/wal-g/internal/databases/postgres.(*BackupHandler).HandleBackupPush
wal-g-1  |      /home/runner/work/wal-g/wal-g/internal/databases/postgres/backup_push_handler.go:388
wal-g-1  | github.com/wal-g/wal-g/cmd/pg.init.func11
wal-g-1  |      /home/runner/work/wal-g/wal-g/cmd/pg/backup_push.go:117
wal-g-1  | github.com/spf13/cobra.(*Command).execute
wal-g-1  |      /home/runner/work/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:860
wal-g-1  | github.com/spf13/cobra.(*Command).ExecuteC
wal-g-1  |      /home/runner/work/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:974
wal-g-1  | github.com/spf13/cobra.(*Command).Execute
wal-g-1  |      /home/runner/work/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:902
wal-g-1  | github.com/wal-g/wal-g/cmd/pg.Execute
wal-g-1  |      /home/runner/work/wal-g/wal-g/cmd/pg/pg.go:55
wal-g-1  | main.main
wal-g-1  |      /home/runner/work/wal-g/wal-g/main/pg/main.go:8
wal-g-1  | runtime.main
wal-g-1  |      /opt/hostedtoolcache/go/1.22.12/x64/src/runtime/proc.go:271
wal-g-1  | runtime.goexit
wal-g-1  |      /opt/hostedtoolcache/go/1.22.12/x64/src/runtime/asm_amd64.s:1695

### PR DESCRIPTION
**Pull request by sixcorners**
Fixes #2113

I'm not really a golang dev but I think this will improve the error message I'm seeing.

### Database name
Wal-g provides support for many databases, please write down name of database you uses.

PostgreSQL
### Describe what this PR fixes
I don't know why something isn't working.

### Please provide steps to reproduce (if it's a bug)
I don't know what causes the problem.

### Please add config and wal-g stdout/stderr logs for debug purpose

also you can use WALG_LOG_LEVEL=DEVEL for logs collecting
<details><summary>If you can, provide logs</summary>
<p>
```bash
wal-g-1  | ERROR: 2025/11/19 12:55:08.453875 ReadRequestBody: read upload data failed
wal-g-1  | caused by: CompressAndEncrypt: compression failed
wal-g-1  | github.com/wal-g/wal-g/internal.newCompressingPipeWriterError
wal-g-1  |      /home/runner/work/wal-g/wal-g/internal/compress_and_encrypt.go:21
wal-g-1  | github.com/wal-g/wal-g/internal.CompressAndEncrypt.func1
wal-g-1  |      /home/runner/work/wal-g/wal-g/internal/compress_and_encrypt.go:55
wal-g-1  | runtime.goexit
wal-g-1  |      /opt/hostedtoolcache/go/1.22.12/x64/src/runtime/asm_amd64.s:1695
wal-g-1  | failed to upload 'basebackups_005/base_000000010000000000000042/tar_partitions/part_001.tar.lz4' to bucket 'qddAhsGKklGSBKfL7AB6'
wal-g-1  | github.com/wal-g/wal-g/pkg/storages/s3.(*Uploader).upload
wal-g-1  |      /home/runner/work/wal-g/wal-g/pkg/storages/s3/uploader.go:107
wal-g-1  | github.com/wal-g/wal-g/pkg/storages/s3.(*Folder).PutObjectWithContext
wal-g-1  |      /home/runner/work/wal-g/wal-g/pkg/storages/s3/folder.go:76
wal-g-1  | github.com/wal-g/wal-g/internal/multistorage.Folder.PutObjectToFirst
wal-g-1  |      /home/runner/work/wal-g/wal-g/internal/multistorage/folder.go:460
wal-g-1  | github.com/wal-g/wal-g/internal/multistorage.Folder.PutObjectWithContext
wal-g-1  |      /home/runner/work/wal-g/wal-g/internal/multistorage/folder.go:443
wal-g-1  | github.com/wal-g/wal-g/internal.(*RegularUploader).Upload
wal-g-1  |      /home/runner/work/wal-g/wal-g/internal/uploader.go:178
wal-g-1  | github.com/wal-g/wal-g/internal/databases/postgres.(*StreamingBaseBackup).Upload
wal-g-1  |      /home/runner/work/wal-g/wal-g/internal/databases/postgres/streaming_base_backup.go:135
wal-g-1  | github.com/wal-g/wal-g/internal/databases/postgres.(*BackupHandler).runRemoteBackup
wal-g-1  |      /home/runner/work/wal-g/wal-g/internal/databases/postgres/backup_push_handler.go:553
wal-g-1  | github.com/wal-g/wal-g/internal/databases/postgres.(*BackupHandler).createAndPushRemoteBackup
wal-g-1  |      /home/runner/work/wal-g/wal-g/internal/databases/postgres/backup_push_handler.go:452
wal-g-1  | github.com/wal-g/wal-g/internal/databases/postgres.(*BackupHandler).handleBackupPushRemote
wal-g-1  |      /home/runner/work/wal-g/wal-g/internal/databases/postgres/backup_push_handler.go:407
wal-g-1  | github.com/wal-g/wal-g/internal/databases/postgres.(*BackupHandler).HandleBackupPush
wal-g-1  |      /home/runner/work/wal-g/wal-g/internal/databases/postgres/backup_push_handler.go:388
wal-g-1  | github.com/wal-g/wal-g/cmd/pg.init.func11
wal-g-1  |      /home/runner/work/wal-g/wal-g/cmd/pg/backup_push.go:117
wal-g-1  | github.com/spf13/cobra.(*Command).execute
wal-g-1  |      /home/runner/work/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:860
wal-g-1  | github.com/spf13/cobra.(*Command).ExecuteC
wal-g-1  |      /home/runner/work/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:974
wal-g-1  | github.com/spf13/cobra.(*Command).Execute
wal-g-1  |      /home/runner/work/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:902
wal-g-1  | github.com/wal-g/wal-g/cmd/pg.Execute
wal-g-1  |      /home/runner/work/wal-g/wal-g/cmd/pg/pg.go:55
wal-g-1  | main.main
wal-g-1  |      /home/runner/work/wal-g/wal-g/main/pg/main.go:8
wal-g-1  | runtime.main
wal-g-1  |      /opt/hostedtoolcache/go/1.22.12/x64/src/runtime/proc.go:271
wal-g-1  | runtime.goexit
wal-g-1  |      /opt/hostedtoolcache/go/1.22.12/x64/src/runtime/asm_amd64.s:1695
```
</p>
</details>

### CODE REVIEW

File: internal/compress_and_encrypt.go [hunk 1]
```diff
@@ -17,8 +17,8 @@ type CompressAndEncryptError struct {
 	error
 }
 
-func newCompressingPipeWriterError(reason string) CompressAndEncryptError {
-	return CompressAndEncryptError{errors.New(reason)}
+func newCompressingPipeWriterError(reason string, cause error) CompressAndEncryptError {
+	return CompressAndEncryptError{errors.Wrap(cause, reason)}
```
Comment (ostinru) [inline internal/compress_and_encrypt.go]: Let's rewrite this to: when `cause` is `nil` - use `errors.New` otherwise `errors.Wrap`... 
It doesn't matter for now, but can lead to cryptic errors in future, when someone pass `nil` to this constrictor - `Wrap` will return nil as well =/
https://github.com/pkg/errors/blob/master/errors.go#L185-L187

Comment (sixcorners) [reply internal/compress_and_encrypt.go]: I changed this to wrap initially because I think something from the error is getting lost but when I read this (https://go.dev/blog/go1.13-errors) it said some errors should not be wrapped. I think in java and python we pretty heavily wrap. Do you think this change is a good one? How often do golang people not wrap?  
Not knowing why a connection doesn't work is so bad in my mind that I never really think to not wrap.

Anyway. I made the change.

Comment (ostinru) [reply internal/compress_and_encrypt.go]: The best solution - is to use `fmt.Errorf("something failed: %w)`. However all code nearby uses deprecated `github.com/pkg/errors`, and I don't think that mixing good error handling with global refactoring would be a good idea. So, let's stick to github-errors.

**Review by ostinru — APPROVED** [review]

**Comment by ostinru** [comment]
Merged. Thank you for your contribution, @sixcorners!
