### PR TITLE
postgresql: fix data path mismatch on local backups

### LINKED ISSUE #1382: wal-g pgsql: local backup fails if path to "data" on command line is relative instead of absolute
### Database name

postgresql

# Issue description

When run `wal-g backup-push path/to/data/directory`, en error is triggered when `path/to/data/directory` is a relative path.

### Describe your problem

with a correct wal-g.json file, run `wal-g --config wal-g.json backup_push ../pgsql/data`  <- point to the data directory with a relative path

expected result : succesful backup from local database

instead :
```
ERROR: 2022/11/16 15:40:51.242628 Data directory read from Postgres (../pgsql/data) is different than as parsed (/home/dbuser/pgsql/data).
panic: Data directory read from Postgres (../pgsql/data) is different than as parsed (/home/dbuser/pgsql/data).

goroutine 1 [running]:
log.(*Logger).Panicf(0xc000146d20?, {0x1a8bdbb?, 0x10?}, {0xc000a7fae0?, 0x203000?, 0x203000?})
        /home/user/go/src/log/log.go:258 +0x74
github.com/wal-g/wal-g/internal/databases/postgres.(*BackupHandler).HandleBackupPush(0xc000503860)
        /home/user/code/github.com/LeGEC/wal-g/internal/databases/postgres/backup_push_handler.go:331 +0x3fd
github.com/wal-g/wal-g/cmd/pg.glob..func4(0x2c1bd80?, {0xc00063bb60, 0x1, 0x3?})
        /home/user/code/github.com/LeGEC/wal-g/cmd/pg/backup_push.go:97 +0x732
...
```

### PR DESCRIPTION
**Pull request by LeGEC**
### Database name

postgresql

# Pull request description

### Describe what this PR fix

fixes #1382 

expand data path from command line to an absolute path before resolving symlinks and comparing it to value returned from pgsql.

### CODE REVIEW

File: internal/databases/postgres/backup_push_handler.go [hunk 1]
```diff
@@ -304,33 +304,46 @@ func (bh *BackupHandler) uploadBackup() internal.TarFileSets {
...
+	tracelog.InfoLogger.Println("To run with local backup functionalities, supply [db_directory].")
+	if bh.PgInfo.pgVersion < 110000 && !bh.Arguments.verifyPageChecksums {
+		tracelog.InfoLogger.Println("VerifyPageChecksums=false is only supported for streaming backup since PG11")
+		bh.Arguments.verifyPageChecksums = true
+	}
+	bh.createAndPushRemoteBackup()
+}
+
+func (bh *BackupHandler) handleBackupPushLocal() {
+	{
```
Comment (serprex) [inline internal/databases/postgres/backup_push_handler.go:333]: Why wrap this block in curlies?

Comment (LeGEC) [reply internal/databases/postgres/backup_push_handler.go:333]: a habit I have to scope variables that are short lived. For example : we *know* that `fromServer` and `fromCli` have no impact after `}`.

If you think this is weird feel free to remove them.

**Review by serprex — APPROVED** [review]

**Review by usernamedt — APPROVED** [review]

**Comment by usernamedt** [comment]
Looks good, thanks for you contribution!
